COMPUTE = [
    "ADD",
    "ADDMOD",
    "ADDRESS",
    "AND",
    "BASEFEE",
    "BLOBBASEFEE",
    "BLOBHASH",
    "BLOCKHASH",
    "BYTE",
    "CALLDATALOAD",
    "CALLDATASIZE",
    "CALLER",
    "CALLVALUE",
    "CHAINID",
    "CODESIZE",
    "COINBASE",
    "DIV",
    "DIFFICULTY",
    "DUP",
    "EQ",
    "EXP",
    "GAS",
    "GASLIMIT",
    "GASPRICE",
    "GT",
    "INVALID",
    "ISZERO",
    "JUMP",
    "JUMPDEST",
    "JUMPI",
    "LT",
    "MOD",
    "MSIZE",
    "MUL",
    "MULMOD",
    "NOT",
    "NUMBER",
    "OR",
    "ORIGIN",
    "PC",
    "POP",
    "PREVRANDAO",
    "PUSH",
    "PUSH0",
    "RETURNDATASIZE",
    "SAR",
    "SDIV",
    "SELFBALANCE",
    "SGT",
    "SHL",
    "SHR",
    "SIGNEXTEND",
    "SLT",
    "SMOD",
    "STOP",
    "SUB",
    "SWAP",
    "TIMESTAMP",
    "TLOAD",
    "TSTORE",
    "XOR",
]
ACCESS = ["BALANCE", "EXTCODESIZE", "EXTCODEHASH", "SLOAD"]
MEMORY_0 = ["RETURN", "REVERT"]
MEMORY_3 = [
    "MCOPY",
    "MLOAD",
    "MSTORE",
    "MSTORE8",
    "CALLDATACOPY",
    "CODECOPY",
    "RETURNDATACOPY",
]
MEMORY_30 = ["KECCAK256"]
CREATE = ["CREATE", "CREATE2"]
EXTCODECOPY = ["EXTCODECOPY"]
LOG = ["LOG0", "LOG1", "LOG2", "LOG3", "LOG4"]
CALLS = ["DELEGATECALL", "STATICCALL", "CALL", "CALLCODE"]
SSTORE = ["SSTORE"]
SELFDESTRUCT = ["SELFDESTRUCT"]
